# Generated by Django 5.0.6 on 2024-05-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
