# Generated by Django 5.0.6 on 2024-05-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
